# Generated by Django 3.0.3 on 2020-02-19 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCategoria', models.CharField(default='S/A', max_length=200)),
                ('descripcionCategoria', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreMarca', models.CharField(default='S/A', max_length=200)),
                ('telefonoMarca', models.IntegerField(max_length=12)),
                ('descripcionMarca', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='modelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreModelo', models.CharField(default='S/A', max_length=200)),
                ('descripcion', models.CharField(default='', max_length=300)),
                ('categoriaModelo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Catalogo.Categoria')),
                ('marcaModelo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Catalogo.Marca')),
            ],
        ),
    ]
