# Generated by Django 3.0.3 on 2020-02-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='telefonoMarca',
            field=models.IntegerField(),
        ),
    ]
